### ISSUE TITLE
Running example.py using instructions causes error

### ISSUE THREAD

**Issue by alter-sachin** [autognc/starfish#2]
Hi I am trying to run the example.py file in your repo named as script2.py on my desktop with starfish using the instructions .
blender file.blend --python script2.py --background

`Read blend: /home/sachin/Desktop/file.blend
Traceback (most recent call last):
  File "/home/sachin/Desktop/script2.py", line 14, in <module>
    distance=np.linspace(10, 50, num=100)
  File "/home/sachin/.config/blender/2.79/scripts/addons/modules/starfish/core/sequence.py", line 101, in standard
    return cls([Frame(**args) for args in kwargs_per_frame])
  File "/home/sachin/.config/blender/2.79/scripts/addons/modules/starfish/core/sequence.py", line 101, in <listcomp>
    return cls([Frame(**args) for args in kwargs_per_frame])
  File "/home/sachin/.config/blender/2.79/scripts/addons/modules/starfish/core/frame.py", line 59, in __init__
    self.background = Spherical.from_other(background)
  File "/home/sachin/.config/blender/2.79/scripts/addons/modules/starfish/rotations.py", line 74, in from_other
    roll_quat = inv_rot_quat @ obj
TypeError: unsupported operand type(s) for @: 'Quaternion' and 'Quaternion'

Blender quit`

**Comment by cSchubes** [comment]
Thank you for alerting us, this is being looked at now.

**Comment by kvablack** [comment]
My apologies, but Starfish requires Blender 2.8+.  This wasn't clear before, and the documentation has been updated.

Also, you probably don't want to run `example.py` as-is without modifications, since you probably don't have the exact same setup. For starting out, I would recommend opening Blender and running scripts manually from the 'Scripting' tab, first getting a feel for individual frames and then sequences.

Let me know if you have any more questions!
